BuildCLI/BuildCLI

src/main/java/org/buildcli/core/ProjectCompiler.java, src/main/java/org/buildcli/core/ProjectInitializer.java, src/main/java/org/buildcli/core/ProjectRunner.java, src/main/java/org/buildcli/utils/PomUtils.java, src/main/java/org/buildcli/utils/SystemCommands.java
- String concatenation replaced for text block;
- Change ProcessBuild to run on Windows, MacOS and Linux;
- Changed option '-c' to use maven in quiet mode, '-q';
=> Improve code design

src/main/java/org/buildcli/model/Dependency.java, src/main/java/org/buildcli/model/Pom.java, src/main/java/org/buildcli/utils/PomUtils.java, src/test/java/org/buildcli/utils/PomUtilsTest.java, src/test/resources/pom-utils-test/non-dependencies-pom.xml
POM data loading has been refactored to be done via JAXP
=> Refactor pomData loading with JAXP

README.md, src/main/java/org/buildcli/OptionCommand.java, src/main/java/org/buildcli/OptionCommandMap.java, src/main/java/org/buildcli/core/ProjectCompiler.java, src/main/java/org/buildcli/core/ProjectInitializer.java, src/main/java/org/buildcli/core/ProjectRunner.java, src/main/java/org/buildcli/utils/DockerBuildRunner.java, src/main/java/org/buildcli/utils/DockerManager.java
This PR introduces Docker support for the BuildCLI project. Two new commands were added to simplify the process of containerizing and running Java applications in Docker:
- `buildcli --dockerize`: Generates a `Dockerfile` to set up a Docker container for Java projects.
- `buildcli --docker-build`: Builds and runs the Docker container based on the generated `Dockerfile`.
These changes improve the project's compatibility with containerized environments, making it easier for developers to deploy their applications using Docker.
N/A
- `--dockerize` only generates the Dockerfile.
- `--docker-build` handles the Docker build and run processes.
- `DockerManager`: Enhanced to manage Docker-related tasks.
- Added proper logging and error handling for Docker commands.
- Verified that `buildcli …
=> feat: add Docker support with build and run commands

README.md, src/main/java/org/buildcli/BuildCLI.java, src/main/java/org/buildcli/OptionCommand.java, src/main/java/org/buildcli/OptionCommandMap.java, src/main/java/org/buildcli/core/ProjectInitializer.java, src/main/java/org/buildcli/utils/ReleaseManager.java, src/main/java/org/buildcli/utils/SemVerManager.java
This PR introduces semantic versioning and release automation functionality to the BuildCLI tool. It includes commands for managing project versions and automating the release process, making it easier for developers to maintain consistent versioning and release workflows.
Fixes #19 - Add support for semantic versioning and automated releases.
- Updates the `VERSION` file based on the specified version type.
- Ensures compliance with semantic versioning standards.
- Generates a `CHANGELOG.md` with details of the latest changes.
- Tags the release in Git using the current version.
- Verified the correct update of the `VERSION` file for major, minor, and patch increments.
- Developers can now automate versioning and releases directly from BuildCLI, streamlining their workflows.
- Future …
=> feat: Add semantic versioning and release automation

CODE_OF_CONDUCT.md
Every good open source project for the community requires a code of conduct.
It's only a propose, feel free to accept or decline.
=> Community Standards - Code of Conduct

src/main/java/org/buildcli/OptionCommand.java, src/main/java/org/buildcli/OptionCommandMap.java, src/main/java/org/buildcli/utils/DirectoryCleanup.java, src/main/java/org/buildcli/utils/ProjectCleanup.java, src/test/resources/pom-core-test/pom.xml.versionsBackup
Add --cleanup command, to remove target folder (if exists).
=> feat: add --cleanup command, to remove 'target' folder

.gitignore, Dockerfile, pom.xml, src/main/java/org/buildcli/OptionCommand.java, src/main/java/org/buildcli/OptionCommandMap.java, src/main/java/org/buildcli/utils/MavenInstaller.java, src/main/java/org/buildcli/utils/OS.java, src/main/java/org/buildcli/utils/SystemCommands.java, src/main/java/org/buildcli/utils/compress/FileExtractor.java, src/main/java/org/buildcli/utils/tools/ToolChecks.java
Hi, I implemented this feature, but, I only test on Linux.
=> Installing maven if is not installed in user machine

pom.xml
=> Updating logback dependencies

src/main/java/org/buildcli/commands/project/AddCommand.java
Added descriptions to the following commands of project: AddCommand
[ISSUE-121](https://github.com/wheslleyrimar/BuildCLI/issues/121)
=> [FEAT] [ISSUE-121] Adding description to add command

src/main/java/org/buildcli/domain/git/GitCommandExecutor.java, src/main/java/org/buildcli/domain/git/GitCommands.java
=> Fixes check updates

src/main/java/org/buildcli/commands/project/InitCommand.java
=> feat(project-init): Add description for init command in CLI help

src/main/java/org/buildcli/commands/project/add/DependencyCommand.java, src/main/java/org/buildcli/commands/project/add/DockerfileCommand.java, src/main/java/org/buildcli/commands/project/add/ProfileCommand.java, src/main/java/org/buildcli/commands/project/rm/DependencyCommand.java, src/main/java/org/buildcli/commands/project/rm/ProfileCommand.java, src/main/java/org/buildcli/commands/project/run/DockerfileCommand.java
We dont have issue open but talking to Matheus, we decided to add description to subcommands
=> feat: adding description to subcommands

.github/CONTRIBUTING.md
issue #170 
i have created complete new contributing.md guide using previous and readme keeping in mind.
=> Updated Contribution Guidelines to Avoid Parallel Work on Same Issue

.github/workflows/greetings.yaml
=> Automatic Greetings for First-Time Contributors and PRs

.github/workflows/auto-assign.yml
=> fix/ adjustment of auto-assign workflow

CODE_OF_CONDUCT.md, README.md
=> Fixed almost all lint issue in Readme.md and Code_Of_Conduct.md

src/main/java/org/buildcli/BuildCLI.java, src/main/java/org/buildcli/actions/commandline/JavaProcess.java, src/main/java/org/buildcli/commands/ProjectCommand.java, src/main/java/org/buildcli/commands/RunCommand.java, src/main/java/org/buildcli/commands/run/DockerfileCommand.java, src/main/java/org/buildcli/exceptions/ThrowingComandExecutor.java, src/main/java/org/buildcli/exceptions/ThrowingComandExecutorWrapper.java
Add run command to run jar files, java file and java project, all in one.
Fixes #148
=> feat: extends run command functionality, run jar file and .java file

.github/workflows/close-issue-on-pr-merge.yaml
fixes #195 
Runs when a PR is merged, Scans the PR description for linked issues (Closes #123, Fixes #456, etc.) Automatically closes the referenced issue using GitHub’s API.
=> Issue Auto-Closing Automation 

src/main/java/org/buildcli/CommandExecutor.java, src/main/java/org/buildcli/actions/commandline/AbstractCommandLineProcess.java, src/main/java/org/buildcli/actions/commandline/BuildTool.java, src/main/java/org/buildcli/actions/commandline/DockerProcess.java, src/main/java/org/buildcli/actions/commandline/GradleProcess.java, src/main/java/org/buildcli/actions/commandline/JavaProcess.java, src/main/java/org/buildcli/actions/commandline/MavenProcess.java, src/main/java/org/buildcli/commands/project/add/ProfileCommand.java, src/main/java/org/buildcli/commands/project/set/EnvironmentCommand.java
=> Fix: run project not print

core/src/main/java/dev/buildcli/core/constants/ChangelogConstants.java, core/src/main/java/dev/buildcli/core/utils/FileTypes.java
=> fix: Update package declarations to reflect new structure

cli/src/main/java/dev/buildcli/cli/CommandLineRunner.java, cli/src/main/java/dev/buildcli/cli/commands/ConfigCommand.java, cli/src/main/java/dev/buildcli/cli/commands/config/ListCommand.java, core/src/main/java/dev/buildcli/core/domain/configs/BuildCLIConfig.java, core/src/main/java/dev/buildcli/core/utils/BuildCLIService.java
I added dynamic config to print banner.
Config property to:
- Enable: `buildcli.logging.banner.enabled`;
- Path: `buildcli.logging.banner.path`;
=> feat: add print banner config

.github/labeler.yml, .github/workflows/auto-label.yaml
=> Automatic Labeling of Issues and PRs

cli/src/test/java/dev/buildcli/cli/core/BuildCLIServiceTest.java, core/src/main/java/dev/buildcli/core/utils/BuildCLIService.java, pom.xml
This PR refactors the BuildCLIService class to improve its testability, ensuring that tests are applied only to public methods.
Unit Tests: BuildCLIService.java #301 
- `testWelcome()`: Verifies if the welcome message is printed correctly.
- `testShouldShowAsciiArt()`: Ensures ASCII art is displayed for relevant commands.
- `testAbout()`: Mocks GitCommandExecutor to test repository contribution output.
- `testCheckUpdatesBuildCLIAndUpdateTrue()`: Simulates an outdated repository scenario and checks if the update process is triggered.
- `testCheckUpdatesBuildCLIAndUpdateFalse()`: Ensures no output is generated when the repository is already up to date.
=> Test/build cli service test  #301

core/src/test/java/dev/buildcli/core/constants/MavenConstantsTest.java
=>  Unit Tests: MavenConstants.java #442

core/src/test/java/dev/buildcli/core/actions/changelog/ChangelogConstantsTest.java, core/src/test/java/dev/buildcli/core/constants/ConfigDefaultConstantsTest.java, core/src/test/java/dev/buildcli/core/constants/MavenConstantsTest.java
=> Unit Tests: ChangelogConstants.java #439

core/src/main/java/dev/buildcli/core/actions/commandline/JavaProcess.java, core/src/test/java/dev/buildcli/core/actions/commandline/JavaProcessTest.java
This PR adds unit tests for the `JavaProcess` class.  
- **Unit Tests: JavaProcess.java** [#361](https://github.com/BuildCLI/BuildCLI/issues/361)  
- refactor JavaProcess class: return JavaProcess instead of CommandLineProcess in `createRunClassProcess()`
- Added unit tests for the JavaProcess class.
- Covered creation of Java processes with various arguments (including -jar and class paths).
- Verified version command creation.
- Included validation for command execution and error handling.
=> Unit Tests: JavaProcess.java

README.md
Small change to fix the reference in our README.md to the right path of CONTRIBUTING.md
=> Fix on CONTRIBUTING.md reference inside README.me

cli/src/main/java/dev/buildcli/cli/commands/run/DockerfileCommand.java
- Changing Dockerfile command alias from 'd' to 'df'
=> Changing Dockerfile command alias from 'd' to 'df'
