- src/main/java/org/buildcli/BuildCLI.java
- src/main/java/org/buildcli/utils/Pom.java
- src/main/java/org/buildcli/utils/PomUtils.java
- Improve --add-dependency to replace older entry for the new one with the same gruopId:artifactId, instead of only add a new entry to the file;
- Add capability to remove, --rm-dependency=<gruopId:artifactId> option
N/A
- Create a new class Pom.java that contains pom file properties;
- Refactory the PomUtil.java;
- Add option --rm-dependency to BuildCLI.java
- Add dependency;
- Add one more once the same dependency and open pom.xml life and search for duplicate dependency entries;
- Add the same dependency with the other version search for the entry, and look if it is updated;
- Remove the entry and search in the pom file if the entry was removed;
N/A
> Improve --add-dependency, add option --rm-dependency

- README.md
- pom.xml
- src/main/java/org/buildcli/BuildCLI.java
- src/main/java/org/buildcli/utils/CodeDocumenter.java
This PR introduces an **automated documentation** feature for Java classes in projects generated by BuildCLI, utilizing the local API from Ollama. Now, BuildCLI can request detailed documentation for code and directly insert it into Java files without manual editing.
The changes were tested manually with different Java files in the generated project. The Main.java file was used as an example, and documentation was generated and embedded directly without compilation errors.
1. Tested documentation generation on files with various structures.
2. Verified logs and error messages for handling timeouts and failures from the Ollama API.
3. Confirmed that the documentation was correctly inserted in target files.
This feature can be expanded to support multiple files in a single run or to …
> feat: add AI-powered Java file documentation feature

- src/main/java/org/buildcli/BuildCLI.java
- src/main/java/org/buildcli/OptionCommand.java
- src/main/java/org/buildcli/utils/CodeDocumenter.java
This PR enhances the `buildcli --document-code` functionality to process both individual files and entire directories. When a directory is provided, all Java files within that directory will be documented. If a specific file is provided, only that file will be documented.
- #17 
- Support for documenting all Java files within a directory.
- Maintains support for documenting individual Java files.
- Added meaningful Javadoc comments.
- Avoids redundant explanations or hypothetical suggestions.
- Preserves the original code structure.
- Graceful handling of invalid inputs (e.g., non-Java files or empty directories).
The following tests were performed:
1. **Single File Test**: Verified that individual Java files are documented correctly with accurate Javadoc comments.
2. **Directory Test**: …
> feat: Enhance code documentation feature for Java projects

- README.md
- src/main/java/org/buildcli/OptionCommand.java
- src/main/java/org/buildcli/OptionCommandMap.java
- src/main/java/org/buildcli/utils/CICDManager.java
This pull request introduces a new feature to integrate BuildCLI with CI/CD tools, enabling developers to automatically create configuration files and trigger pipelines based on project changes. This enhancement simplifies the process of integrating projects into CI/CD environments.
#20
1. Verified the generation of configuration files (`Jenkinsfile`, `.github/workflows/main.yml`) after running `buildcli` commands.
2. Validated YAML syntax using `yamllint`.
3. Simulated workflows locally using tools like `act` (GitHub Actions) and `gitlab-runner` (GitLab CI).
4. Deployed changes to a test repository and monitored pipeline execution on CI/CD platforms.
- The feature is designed to be extensible, allowing support for additional CI/CD tools in the future.
- Documentation for configuring …
> feat: add CI/CD integration support

- src/main/java/org/buildcli/BuildCLI.java
- src/main/java/org/buildcli/log/ColorConsoleHandler.java
- src/main/java/org/buildcli/log/config/LoggingConfig.java
- src/main/resources/logging.properties
- ColorConsoleHandler: defines colors based on log severity
- logging.properties: created a file with ColorConsoleHandler as the default handler for Logger
- LoggingConfig: class to load and identify the configuration file
- BuildCLI: initialize default Logger handler in main
https://github.com/wheslleyrimar/BuildCLI/issues/39
> :card_file_box: feat: add color to log output based on severity | Issue #39 Add Color to Terminal Output 

- README.md
- pom.xml
- src/main/java/org/buildcli/OptionCommand.java
- src/main/java/org/buildcli/OptionCommandMap.java
- src/main/java/org/buildcli/utils/BuildCLIIntro.java
- src/main/java/org/buildcli/utils/ReleaseManager.java
Displays project information, including its purpose, repository, and contributors.
Fixes #46 - Add an --about Command
- Purpose of BuildCLI
- The project's repository
- A list of voluntary contributors
- ```runGitCommandAndShowOutput```: Executes a Git command and captures its output, throwing an exception if the command fails.
- ```showContributors```: Retrieves and return the list of contributors from a local Git repository.
- ```findGitRepository```: Finds the path of a local Git repository based on the given directory path.
- ```getBuildCLIBuildDirectory```: Retrieves the build directory path from the MANIFEST.MF file inside the JAR.
- ```about```: Displays project purpose, repository and contributors.
- Git command executed in the home directory, but displaying the result from …
> feat: Implemented an --about Command | Issue #46

- src/main/java/org/buildcli/log/SystemOutLogger.java
- src/main/resources/logback.xml
- Removed extra newlines in SystemOutLogger to prevent cluttered logs  
- Disabled Logback internal logs to reduce noise  
- Fixed appender-ref warnings in logback.xml  
- Set log level to INFO for cleaner output
> fix(logging): Clean up log output and fix Logback config

- .github/workflows/maven.yml
This PR fixes an issue with updating the dependency graph in GitHub Actions. The workflow was failing with a `403 Forbidden` error due to missing permissions for `security-events`. This fix explicitly adds the required permission and updates the dependency submission action to the latest stable version.
- Verified that the workflow executes correctly without `403 Forbidden` errors.  
- Checked GitHub Actions logs to confirm that dependencies are submitted successfully.  
- Manually triggered the workflow on a test branch to validate changes.  
- If the error persists, consider switching to a **Personal Access Token (PAT)** for submitting dependency graphs.  
- This fix improves Dependabot alerts by ensuring GitHub can process the full dependency tree.
> fix: update dependency graph permissions

- src/main/java/org/buildcli/commands/VersionCommand.java
Change requested by reviewer [@omatheusmesmo ] on PR #92
> Update description to specify BuildCLI instead of CLI in version command

- .github/workflows/maven.yml
- README.md
- src/main/java/org/buildcli/commands/ProjectCommand.java
- src/main/java/org/buildcli/commands/project/AddCommand.java
- src/main/java/org/buildcli/commands/project/BuildCommand.java
- src/main/java/org/buildcli/commands/project/CleanupCommand.java
- src/main/java/org/buildcli/commands/project/DocumentCodeCommand.java
- src/main/java/org/buildcli/commands/project/InitCommand.java
- src/main/java/org/buildcli/commands/project/RmCommand.java
- src/main/java/org/buildcli/commands/project/TestCommand.java
- src/main/java/org/buildcli/commands/project/UpdateCommand.java
I made a few changes because the guide was still incorrect. With these updates, new users will have a better first impression. ☕
I removed some aliases in the command descriptions to avoid redundant information.
> Correct installation instructions in README.md e removal of aliases in the command description

- README.md
- install.bat
- install.sh
The script automates the installation of BuildCLI by cloning the repository, verifying dependencies (Java and Maven), building the project, and configuring it for global access. On Unix-like systems, it also creates a script that allows running the project using the buildcli command.
> Create a Multiplatform Installation Script - Issue 100

- src/main/java/org/buildcli/utils/BuildCLIIntro.java
This PR updates the outdated repository URL in the `about()` method of `BuildCLIIntro.java` to point to the correct repository link: https://github.com/BuildCLI/BuildCLI.
> Fix: Update repository URL in about() method (#207)

- install.bat
- install.sh
This pull request addresses issue #205 by modifying the installation scripts for Unix-like and Windows systems. 
The new behavior first checks if the repository directory exists:
- If **not present**, the script clones the repository as usual.
- If **already present**, the script performs a git pull to ensure the latest updates.
- Updated **bash script** to check for the existing BuildCLI directory before cloning.
- If the directory exists, a git pull is executed instead.
- Applied the same logic to the **windows batch script**, ensuring consistency.
- Ran the unix script:
- Verified that the script skips cloning and pulls the latest changes when the directory exists.
- Confirmed that it correctly clones when the directory is absent.
- Ran the Windows script with similar validations.
Let …
> fix(install): check if repo exists before cloning, pull if it does (bash & bat)

- cli/src/main/java/dev/buildcli/cli/CommandLineRunner.java
- core/src/main/java/dev/buildcli/core/utils/BuildCLIService.java
This PR updates the ASCII Art display logic in BuildCLI to ensure it only appears for specific commands. Previously, the ASCII Art was shown for all commands, which cluttered the terminal output. Now, it will only be displayed when executing the following commands:
- `buildcli p i -n myproject` (or `buildcli project i -n myproject`)
- `buildcli p run` (or `buildcli project run`)
- `buildcli about` (or `buildcli a`)
- `buildcli help`
- Any command that ends with `--help` (e.g., `buildcli p --help`, `buildcli config --help`)
For all other commands, the ASCII Art will no longer be displayed, keeping the CLI output cleaner and more concise.
Fixes #256
The changes were tested by executing different commands in BuildCLI and verifying that the ASCII Art only appears in the correct scenarios. …
> feat: restrict ASCII Art display to specific commands with aliases

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/documentation_update.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/other.yml
fixes #264 
- Created `.github/ISSUE_TEMPLATE/` directory (if not already present)
- Added Bug Report template
- Added Feature Request template
- Added Documentation Update template
- Added Others template
> feat: Add issue templates for bug reports, feature requests, documentation updates, and others

- README.md
- core/src/main/java/dev/buildcli/core/utils/BuildCLIService.java
Updated the repository link in the "about" command of BuildCLI to reflect the new organization URL
> fix: update repo link

- core/src/main/java/dev/buildcli/core/utils/BuildCLIService.java
I have adjusted the logic of the generateBuildCLIJar() method to correctly display success and failure messages based on the update process exit code.
🔹 Commit: e0c91353420b505bf7c6fd1ee1e06abb574e5acf
🔹 Issue: #288
Please review it and let me know if any further changes are needed.
> fix: correct incorrect auto update status message #288

- cli/src/main/java/dev/buildcli/cli/commands/RunCommand.java
- cli/src/main/java/dev/buildcli/cli/commands/project/set/EnvironmentCommand.java
- core/src/main/java/dev/buildcli/core/project/ProjectRunner.java
- core/src/main/java/dev/buildcli/core/utils/ProfileManager.java
This PR addresses issue #324, where running `buildcli p run` without an active profile or missing configuration files resulted in `NoSuchFileException` errors in the logs. The changes ensure a more graceful handling of missing files and improve the user experience by providing clear warnings instead of throwing exceptions.
---
- The `getActiveProfile` method now logs a warning and defaults to the "default" profile if `environment.config` is missing.
- The `loadProfileProperties` method logs a warning and returns empty properties if the profile-specific properties file (e.g., `application-default.properties`) is missing.
- Replaced exception throwing with warning logs for missing files, ensuring cleaner and more user-friendly output.
- Added descriptive warning messages to inform users …
> fix: Handle missing profile and properties files gracefully

- cli/src/main/java/dev/buildcli/cli/BuildCLI.java
- cli/src/main/java/dev/buildcli/cli/commands/BugCommand.java
- cli/src/main/java/dev/buildcli/cli/commands/bug/BugCommand.java
- core/src/main/java/dev/buildcli/core/utils/JavaUtils.java
- core/src/main/java/dev/buildcli/core/utils/OS.java
Adds the initial implementation of the `bug` command, which opens a GitHub issue template pre-filled with system and version info. This feature helps users report bugs in BuildCLI more easily.
#450 
- Manually tested on macOS by running `buildcli bug` and verifying that the correct issue page opens in the browser.
- Checked output when the browser is not supported, ensuring a fallback message is printed.
- Future improvements include dynamically fetching the BuildCLI version from a configuration file or manifest.
> feat: add bug report command (WIP)

- core/src/test/java/dev/buildcli/core/actions/tools/JDKCheckerTest.java
This PR adds unit tests for the `JDKChecker` class.  
- **Unit Tests: JDKChecker.java** [#357 ](https://github.com/BuildCLI/BuildCLI/issues/357)  
- Added unit tests for the `JDKChecker` class.  
- Covered checks for JDK installation status.  
- Implemented tests to retrieve JDK version when installed and return "N/A" when not installed or output is malformed.  
- Verified that the installation instructions URL is returned correctly.  
- Implemented a test to ensure the correct message is printed when fixing JDK issues.  
> test: Add unit tests for JDKChecker class

- core/src/test/java/dev/buildcli/core/actions/tools/ToolCheckersTest.java
This PR adds unit tests for the `ToolCheckers` class.  
- **Unit Tests: ToolCheckers.java** [#356](https://github.com/BuildCLI/BuildCLI/issues/356)  
- Added unit tests for the `ToolCheckers` class.  
- Covered the `all()` method to validate the list of `ToolChecker` instances.  
- Implemented checks to verify that the list returned contains `JDKChecker`, `MavenChecker`, `GradleChecker`, and `DockerChecker` in the correct order.  
> test: add unit test for ToolCheckers class

- core/src/test/java/dev/buildcli/core/actions/commandline/DockerProcessTest.java
This PR adds unit tests for the `DockerProcess` class.  
- **Unit Tests: DockerProcess.java** [#364](https://github.com/BuildCLI/BuildCLI/issues/364)  
- Added unit tests for the `DockerProcess` class.  
- Covered tests for creating build, run, and general Docker processes with and without parameters.  
- Verified that the correct version and info commands are created.  
> Add unit tests for DockerProcess methods

- core/src/test/java/dev/buildcli/core/actions/tools/DockerCheckerTest.java
This PR adds unit tests for the `DockerChecker` class.  
- **Unit Tests: DockerChecker.java** [#358 ](https://github.com/BuildCLI/BuildCLI/issues/358)  
- Added unit tests for the `DockerChecker` class.  
- Covered checks for Docker installation status.  
- Implemented tests to retrieve Docker version when installed and return "N/A" when not installed or output is malformed.  
- Verified that install instructions URL is returned correctly.  
> test: Add unit tests for DockerChecker class

- core/src/test/java/dev/buildcli/core/actions/tools/GradleCheckerTest.java
This PR adds unit tests for the `GradleChecker` class.  
- **Unit Tests: GradleChecker.java** [#355](https://github.com/BuildCLI/BuildCLI/issues/355)  
- Added unit tests for the `GradleChecker` class.  
- Covered checks for Gradle installation status.  
- Implemented tests to retrieve Gradle version when installed and return "N/A" when not installed or output is malformed.  
- Verified that install instructions URL is returned correctly.  
- Ensured `GradleInstaller` is called when `gradleChecker.fixIssue()` is invoked.  
> test: Add unit tests for GradleChecker class

- core/src/test/java/dev/buildcli/core/model/DependencyTest.java
- core/src/test/java/dev/buildcli/core/model/PomTest.java
- core/src/test/resources/pom-core-test/pom.xml
- core/src/test/resources/pom-core-test/pom.xml.versionsBackup
- core/src/test/resources/pom-utils-test/non-dependencies-pom.xml
- core/src/test/resources/pom-utils-test/pom.xml
Adds a new test class, `PomTest.java`, to cover:
- Adding dependencies by string (`groupId:artifactId:version`).
- Removing dependencies (both string and parameter-based).
- Verifying `hasDependency(...)` checks.
- Testing `getDependency(...)`, `countDependencies()`, and `toString()`.
- Ensuring `getDependencyFormatted()` returns valid XML.
- Created `PomTest.java` under `core/src/test/java/dev/buildcli/core/model`.
- Verified edge cases (e.g., default version = "LATEST" for 2-part dep strings).
Closes #443
> Add Unit Tests for Pom.java (Closes #443)

- core/src/test/java/dev/buildcli/core/actions/tools/MavenCheckerTest.java
- core/src/test/java/dev/buildcli/core/utils/actions/MavenCheckerTest.java
This PR adds unit tests for the `MavenChecker` class.
- **Unit Tests: MavenChecker.java** [#353 ](https://github.com/BuildCLI/BuildCLI/issues/353)  
- Added unit tests for the `MavenChecker` class.  
- Covered checks for Maven installation status.  
- Implemented tests to retrieve Maven version when installed and return "N/A" when not installed.  
- Verified that install instructions URL is returned correctly.  
- Ensured `MavenInstaller` is called when `mavenChecker.fixIssue();` with Maven installation.
> test: Add unit tests for MavenChecker class

- core/src/test/java/dev/buildcli/core/exceptions/ConfigExceptionTest.java
Added unit tests for the ConfigException class, covering both constructors (with message and with message + cause). The tests ensure that the values are correctly assigned and that the expected behavior is maintained.
Let me know if any adjustments or improvements are needed! 🚀
> Add unit tests for ConfigException

- core/src/test/java/dev/buildcli/core/utils/compress/FileExtractorTest.java
This PR adds unit tests for the `FileExtractor` class, ensuring proper extraction of `.zip` and `.tar.gz` files, handling of unsupported formats, and permission-related errors.
- **Unit Tests: FileExtractor.java** [#421](https://github.com/BuildCLI/BuildCLI/issues/421)  
- Added unit tests for the `FileExtractor` class.  
- Covered extraction of `.zip` and `.tar.gz` files.  
- Implemented tests for unsupported archive formats.  
- Added a test case to verify extraction failure due to missing read permissions.  
> test: add unit tests for FileExtractor with zip and tar.gz support

- README.md
This PR fixes the broken link on `README.md`.
Closes #538
> fix: `CONTRIBUTING.md` link on `README.md`

- cli/src/test/java/dev/buildcli/cli/core/AboutServiceTest.java
- core/pom.xml
- core/src/test/java/dev/buildcli/core/actions/commandline/GradleProcessTest.java
- core/src/test/java/dev/buildcli/core/actions/commandline/MavenProcessTest.java
- core/src/test/java/dev/buildcli/core/utils/OSTest.java
- core/src/test/resources/pom-core-test/pom.xml
This PR resolves all test failures to ensure mvn clean install passes successfully on windows OS.
key improvements include:
• AboutServiceTest.java proper handling different newline characters (**\n** vs **\r\n**)
• junit-jupiter-api using default version coming from parent/dependency management
• Using Gradle/Maven Constants to use the proper value for maven cmd (mvn/gradle vs mvn.bat/gradle.bat on windows)
• File.canExecute method not reliable, test was failing, now we actually verify that the command isn't executed.
• In shouldNotThrowException_whenChmodXCommandFails if System.setProperty("os.name", "Linux"); not set, test fails on windows.
Before:
After:
> fix(tests) Fix failing tests on windows 10 and correcting junit version

- README.md
- core/src/test/java/dev/buildcli/core/ProjectUpdaterTest.java
This is my first time contributing to open source. Here are the test cases I wrote
UseOldDependencies: Verifies that no updates are made when dependencies are outdated but isUpdateNow is set to false.
AllDependenciesUpToDate: Ensures no changes are made when all dependencies are already up to date.
UpdateOutdatedDependencies: Confirms that outdated dependencies are updated when isUpdateNow is true.
EmptyPomFile: Tests behavior when the pom.xml contains no dependencies.
InvalidPomFile: Validates that an error is thrown when an invalid pom.xml is provided.
> Added Test Cases to ProjectUpdaterTest.java Issue #434

- README.md
Fixed command example from "buildcli project run" to "buildcli run"
> updated typo for example 3 in README
